---
- name: "Install required packages"
  become: true
  yum:
    name: 
      - "ansible"
      - "@Development Tools"
    state: "latest"

- name: "Download Ansible Tower"
  unarchive:
    src: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ tower_setup_version }}.tar.gz
    dest: "{{ tower_setup_dir }}"
    creates: "{{ tower_setup_dir }}/ansible-tower-setup-{{ tower_setup_version }}"
    remote_src: yes

- name: "Generate Configuration"
  become: true
  template:
    backup: true
    src: inventory.j2
    dest: "{{ tower_setup_dir }}/ansible-tower-setup-{{ tower_setup_version }}/inventory"
  notify: "setup_tower"
  register: inventory_config

- name: "force all notified handlers to run *NOW*"
  meta: flush_handlers
