---
- name: "Download Ansible Tower"
  unarchive:
    src: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-{{ tower_setup_version }}.tar.gz
    dest: "{{ tower_setup_dir }}"
    creates: "{{ tower_setup_dir }}/ansible-tower-setup-{{ tower_setup_version }}"
    remote_src: yes
  notify: setup_ansible_tower

- name: "Generate Configuration"
  template:
    src: inventory.j2
    dest: "{{ tower_setup_dir }}/ansible-tower-setup-{{ tower_setup_version }}/inventory"
  notify: setup_ansible_tower

