---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Install dependencies (RedHat).
      yum:
        name: "epel-release"
        state: "present"
      when: ansible_os_family == 'RedHat'

  roles:
    - victorock.tower_setup
